server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuulservice
  cloud:
    config:
      uri: http://localhost:9999



logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes, refresh


zuul:
  ignored-services: config-dev, workservice
  prefix: /api
  routes:
    config-dev: /my-member/**
    workservice: /my-work/**