server:
  port: 8001

spring:
  application:
    name: config-dev
  config:
    import: optional:configserver:http://localhost:9999

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/